name: smartshop_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # shared dependencies
  share_plus: ^9.0.0

  # UI & Tiện ích
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  collection: ^1.18.0 # Thêm collection để dùng firstWhereOrNull
  
  # Quản lý trạng thái
  flutter_riverpod: ^2.5.1

  # Điều hướng
  go_router: ^14.2.0

  graphql_flutter: ^5.2.0-beta.6

  # Lưu trữ bảo mật
  # Dùng để lưu trữ token và thông tin người dùng
  flutter_secure_storage: ^9.2.2 
  image_picker: ^1.1.2
  http: ^1.2.1
  http_parser: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/