name: smartshop_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Tiện ích
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  
  # Quản lý trạng thái
  flutter_riverpod: ^2.5.1

  # Kết nối GraphQL
  graphql_flutter: ^5.2.0-beta.6 

  # Điều hướng
  go_router: ^14.2.0

  # Lưu trữ an toàn
  flutter_secure_storage: ^9.2.2

  # Upload file
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true